services:
  ntfy:
    image: binwiederhier/ntfy:v2.7.0
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=America/Chicago    # optional: Change to your desired timezone
    # user: UID:GID # optional: Set custom user/group or uid/gid
    volumes:
      - ./var/cache/ntfy:/var/cache/ntfy
      - ./var/lib:/var/lib
      #- /run/ntfy/ntfy.sock:/var/lib/ntfy/ntfy.sock
      #- ./var/lib/ntfy/user.db:/var/lib/ntfy/user.db
      - ./var/log:/var/log
      - ./objects/etc/ntfy:/etc/ntfy
    restart: unless-stopped
    ports:
      - '127.0.0.1:8085:80'