version: "2.1"
services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=America/Chicago    # optional: Change to your desired timezone
    # user: UID:GID # optional: Set custom user/group or uid/gid
    volumes:
      - ./var/cache/ntfy:/var/cache/ntfy
      - ./var/lib:/var/lib
      - ./var/log:/var/log
      - ./objects/etc/ntfy:/etc/ntfy
    restart: unless-stopped
